name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout do reposit칩rio principal
        uses: actions/checkout@v3
        with:
          submodules: false
          lfs: false

      - name: Clonar reposit칩rio p칰blico Fontes
        run: |
          echo "游댃 Clonando reposit칩rio p칰blico Fontes..."
          git clone https://github.com/GPincinato/Fontes.git Fontes

      - name: Build and Deploy para Azure Static Web App
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_GRASS_0F10DE810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # para integra칞칚o com PRs
          action: "upload"
          app_location: "/"            # Diret칩rio da app frontend
          api_location: "Fontes"       # API agora clonada localmente
          output_location: ""          # Se houver build est치tico, defina aqui

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Fechar PR no Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_GRASS_0F10DE810 }}
          action: "close"

