name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Clonar repositório privado Fontes
        run: |
          echo "Clonando repositório Fontes..."
          git clone https://x-access-token:${{ secrets.FONTES_PAT }}@github.com/GPincinato/Fontes.git || {
            echo "❌ Falha ao clonar repositório Fontes. Verifique o token ou permissões.";
            exit 1;
          }

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_GRASS_0F10DE810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Para comentários em PRs, etc.
          action: "upload"
          app_location: "/"              # Caminho da aplicação web
          api_location: "Fontes"         # Caminho onde o repo Fontes foi clonado
          output_location: ""            # Diretório de build, se aplicável

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_GRASS_0F10DE810 }}
          action: "close"
